#!/bin/bash
#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

set -e

DEVICE=gtel3g
VENDOR=samsung

MY_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "${MY_DIR}" ]]; then
    MY_DIR="${PWD}"
fi

LINEAGE_ROOT="${MY_DIR}/../../.."
OUTDIR="${LINEAGE_ROOT}/vendor/${VENDOR}/${DEVICE}"

PROPRIETARY_LIST="${MY_DIR}/proprietary-files.txt"

BLOBS_MK="${OUTDIR}/${DEVICE}-vendor-blobs.mk"
PRODUCT_MK="${OUTDIR}/${DEVICE}-vendor.mk"
BOARD_MK="${OUTDIR}/BoardConfigVendor.mk"


mkdir -p "${OUTDIR}"


#
# Parse proprietary-files.txt and generate:
#
#   repository:
#       proprietary/bin/foo
#
#   installed:
#       system/vendor/bin/foo
#
# Special cases:
#
#   cameradata/*
#       -> system/cameradata/*
#
#   vendor/*
#       -> system/vendor/*
#
mapfile -t BLOBS < <(
    python3 - "${PROPRIETARY_LIST}" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])

for raw in path.read_text().splitlines():
    line = raw.strip()

    if not line or line.startswith("#"):
        continue

    # Remove optional pinning hashes.
    spec = line.split("|", 1)[0]

    # Remove optional extract_utils arguments.
    spec = spec.split(";", 1)[0]

    if ":" in spec:
        src, dst = spec.split(":", 1)
    else:
        src = dst = spec

    #
    # extract_utils stores the destination path inside
    # vendor/<vendor>/<device>/proprietary/.
    #
    repo_path = dst

    if dst.startswith("cameradata/"):
        install_path = "system/" + dst

    elif dst.startswith("vendor/"):
        install_path = "system/" + dst

    else:
        install_path = "system/vendor/" + dst

    print(f"{repo_path}|{install_path}")
PY
)


cat > "${BLOBS_MK}" <<EOF2
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# This file is generated by device/${VENDOR}/${DEVICE}/setup-makefiles.sh

PRODUCT_COPY_FILES += \\
EOF2


COUNT="${#BLOBS[@]}"

for ((i = 0; i < COUNT; i++)); do
    ENTRY="${BLOBS[$i]}"

    REPO_PATH="${ENTRY%%|*}"
    INSTALL_PATH="${ENTRY#*|}"

    if [ "$i" -eq $((COUNT - 1)) ]; then
        LINE_END=""
    else
        LINE_END=" \\"
    fi

    printf \
        '    vendor/%s/%s/proprietary/%s:%s%s\n' \
        "${VENDOR}" \
        "${DEVICE}" \
        "${REPO_PATH}" \
        "${INSTALL_PATH}" \
        "${LINE_END}" \
        >> "${BLOBS_MK}"
done


cat > "${PRODUCT_MK}" <<EOF2
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# This file is generated by device/${VENDOR}/${DEVICE}/setup-makefiles.sh

\$(call inherit-product, vendor/${VENDOR}/${DEVICE}/${DEVICE}-vendor-blobs.mk)
EOF2


cat > "${BOARD_MK}" <<EOF2
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# This file is generated by device/${VENDOR}/${DEVICE}/setup-makefiles.sh

USE_CAMERA_STUB := false
EOF2


echo "Generated:"
echo "  ${BLOBS_MK}"
echo "  ${PRODUCT_MK}"
echo "  ${BOARD_MK}"
